### PR TITLE
Update Underground Pass sidebar item requirements

### PR DESCRIPTION
**Pull request by Fincap**
Bucket and Tinderbox can be obtained from the dwarven camp during the quest when they are needed.

Quest sidebar currently doesn't show this:
image

### CODE REVIEW

**Comment by Felanbird** [comment]
The plank can also be obtained during the quest

**Review by Zoinkwiz — CHANGES_REQUESTED** [review]
If we're marking it as obtainable during the quest, we should probably add some checks for 'if you do not have a bucket when you need it, go get the bucket' and such, to avoid people getting lost.

**Comment by Fincap** [comment]
Added in steps to pick up bucket and tinderbox from the dwarven camp.

**Review by Zoinkwiz — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
