### PR TITLE
Achievement Diary Ardougne

### PR DESCRIPTION
**Pull request by Obasill**
Nothing particular to note, fairly straightforward  diary entry. Bunch of TODOs that I'll get to after I'm done the rest of the diaries.

### CODE REVIEW

**Comment by Obasill** [comment]
Oh and like the wildy if you have a completed or even semi completed elite diary can you provide the output of '::getvarp 1197', so I can confirm the bits are lining up

**Review by Zoinkwiz — APPROVED** [review]
Looks really good!

**Comment by Felanbird** [comment]
@Zoinkwiz Don't merge this yet I had a few suggested changes I never suggested, let me check if they've been fixed.

**Review by Felanbird — CHANGES_REQUESTED** [review]
One actual change and the rest just capitalization

**Comment by Zoinkwiz** [comment]
Thanks @Felanbird great suggestions, added them in 😄

**Pull request merged**
