### PR TITLE
Update kandarin easy achievement diary steps per issue #1087

### LINKED ISSUE #1087: Easy Kandarin streamlining
Doing easy kandarin tasks along the guide has you running back and forth around Seers/Catherby quite a bit.

Here's my re-ordered list, you start in Catherby and make your way towards the coal trucks, completing each task as you run east -> west

https://oldschool.runescape.wiki/w/Kandarin_Diary#Easy

\1. Catch a mackerel at Catherby.
\8. Get a pet fish from Harry in Catherby.	
\2. Buy a candle from the candle maker in Catherby. 	
\10. Speak to Sherlock between the Sorcerer's Tower and Keep Le Faye.
\3. Collect 5 flax from the Seers' Village flax field.
\4. Play the Church organ in the Seers' Village church.
\9. Buy a stew from the Seers' Village pub. 	
\7. Defeat one of each elemental in the Elemental Workshop.
\5. Plant jute seeds in the farming patch north of McGrubor's Wood. 	
\6. Have Galahad make you a cup of tea (found in the house west of McGrubor's Wood).
\12. Cross the Coal truck log shortcut.

### PR DESCRIPTION
**Pull request by andersenalan**
Resolves #1087

### CODE REVIEW

**Comment by andersenalan** [comment]
@Zoinkwiz can I get a review? I work in gitlab in my day job so I am unfamiliar with github. I think you need to kick off the workflow.

**Review by Zoinkwiz — CHANGES_REQUESTED** [review]
Hey thanks for tackling this! What you've done should update the sidebar's order, but the order defined in `loadStep()`, as added to the `doEasy` ConditionalStep also needs to be updated to match (like https://github.com/Zoinkwiz/quest-helper/blob/d8f02c9f4d4e0ec48be1295333b4893142de42ff/src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinEasy.java#L102).

Once that's done this should be good to be merged!

**Comment by andersenalan** [comment]
Ah thanks, I had originally changed those but noticed the actual panel didn't change so I backed them out. Was having trouble actually testing since I don't have a new account that can actually complete the steps. I'll make those changes!

**Comment by Zoinkwiz** [comment]
No worries, also if you ever need an account without any tasks done usually you can hop to a quest speedrunning world and have one with no reqs there.

**Pull request merged**
