### PR TITLE
Feature/diary kourend kebos

### PR DESCRIPTION
**Pull request by rileyyy**
Adds the Kourend and Kebos diaries to quest helper.

todo: Elite varps, test other varps (mediums are marked todo if not tested, hards might have all been tested)

### CODE REVIEW

**Review by Obasill — COMMENTED** [review]
It looks good as a start however in the state it is in right now it's almost unusable. I just tested the easy diary and ran into more than a few issues. If the easy diary had this many issues I think it's fair to assume the rest have similar issues. You should definitely take a second look through the entire diary. Some issues were small like not highlighting items but there were also things like the helper leading me to a dead end and having wrong coords / object IDs / NPC IDs. 

Also don't just order the tasks in the order they're given. I had to bounce around the entire continent multiple times just to complete the easy diary. The other diaries are ordered by proximity so I drew a map of each task and started on one side of the map and as the user completed tasks they'd path towards the next closest task.  

I assume you've already completed most of the diary so for testing change the 'false' to 'true' on the varp requirements for tasks you've already completed. Just make sure you've also changed the quest varb so it shows up in your list. 

Lastly keep your branch up to date so it's easier for zoinkwiz to test / approve.

**Comment by rileyyy** [comment]
You're welcome to not use it.  I explained it to the lad I dm'd on discord but I no longer have the time needed to devote to this unfortunately.  He asked that I post a PR for it to make it easier for something or another.

**Comment by Obasill** [comment]
Oh, sorry I didn't know. I'll take some time to fix this up and make sure you're properly credited, you did good work.

**Comment by rileyyy** [comment]
Its all good, didn't mean to come off dick-ish.  I'm not worried about credit if its easier to just start the work over.  Or if you want to fork this, I can drop my PR here

**Comment by Obasill** [comment]
Yeah that sounds good, I've forked and will hopefully have it fixed up in a couple days.

**Pull request closed without merging**
