### PR TITLE
Achievement Diary Morytania

### PR DESCRIPTION
**Pull request by Obasill**
Finally got around to finishing this, sat on elite for a month cause mental stuff. Anyway I know the if statement change in ItemRequirements isn't ideal / makes sense but I figured major changes were out of the scope of making a diary. I mainly want the completion of all diaries by the end of the year, so I'm just making note of things that band-aid fixes and will revisit later. I simply wanted to make sure that the underlying code would work and made a change that would make it actually work.

### CODE REVIEW

**Comment by Obasill** [comment]
Oh also please don't close this to reopen your own PR. I'm trying to use this experience on my resume and when you do that the commit / lines of code no longer show under my name on github.

**Comment by Zoinkwiz** [comment]
Sure. can you clean up the commits then so I can review it then @Obasill

**Comment by Obasill** [comment]
Alright that's about the best I can do, got from ~100 commits to 6. I had fun figuring it out 🙃. @Zoinkwiz

**Comment by Zoinkwiz** [comment]
Added a PR to your repo @Obasill to adjust how the tarn's lair route is done. Lemme know if you disagree with it all, if not merge in and hopefully I can get this merged in 😄

**Comment by Obasill** [comment]
Yeah looks good, I don't think we use tarn's route for anything else but it's a lot easier to read. Fixed the conflicts, good to be merged whenever.

**Review by Zoinkwiz — APPROVED** [review]

**Pull request merged**
